path: '/content/drive/MyDrive/goldfish_dataset' # dataset root dir
train: /content/drive/MyDrive/goldfish_dataset/images/train  # train images (relative to 'path')
val: /content/drive/MyDrive/goldfish_dataset/images/val # val images (relative to 'path')

names:
  0: fish

